name: mightyAdmin
description: A new Flutter application.

version: 2.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  #  firebase crashlytics analytics support
 
  #firebase_analytics: ^9.1.2

  # Used for speed up the coding and font selection
  nb_utils: ^4.4.14
  google_fonts: ^2.3.1

  #  used for API calling and Showing Html data
  http: ^0.13.4
  intl: ^0.17.0
  crypto: ^3.0.1
  html: 0.15.0
  flutter_html: ^2.2.1
  url_launcher: ^6.0.20

  #  Used for Images and icon
  cached_network_image: ^3.2.0
  photo_view: ^0.13.0
  flutter_vector_icons: ^1.0.0
  flutter_speed_dial: ^5.0.0+1
  flutter_staggered_grid_view: ^0.4.1

#  Application information
  #package_info: ^2.0.2
  package_info_plus: ^1.4.0

  #  Used for chart
  syncfusion_flutter_charts: ^19.4.56

  # State Management Technique
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4

  flutter_localizations:
    sdk: flutter
  firebase_crashlytics: ^3.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  # State Management Technique
  build_runner: ^2.1.8
  mobx_codegen: ^2.0.5+2
#flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/flags/
    - lang/




